#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

# Add custom event for aerospace workspace changes
sketchybar --add event aerospace_workspace_change

sketchybar --bar \
    height=22 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    padding_left=14 \
    padding_right=14 \
    notch_width=188 \
    notch_display_height=32

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
    background.color=0xAA494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:12.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5 \
    popup.blur_radius=30 \
    popup.background.color=0xAA494d64 \
    popup.background.corner_radius=8 \
    popup.background.shadow.drawing=on

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify e \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    icon.font="$FONT_FACE:Bold:20.0" \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5a97f \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.color=0xff24273a \
    icon.padding_left=5 \
    icon.padding_right=2 \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    click_script="$PLUGIN_SHARED_DIR/toggle_workspaces_popup.sh" \
    popup.drawing=off \
    popup.horizontal=off \
    --add item current_space.separator left \
    --set current_space.separator \
    background.color=0x00000000 \
    background.padding_left=-8 \
    icon= \
    icon.color=0xfff5a97f \
    icon.font="$FONT_FACE:Bold:20.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item current_space.name left \
    --set current_space.name \
    background.color=0x00000000 \
    background.padding_right=5 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:12.0" \
    label.padding_left=2 \
    label.drawing=yes

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    icon.color=0xff24273a \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    background.padding_left=-3 \
    icon= \
    icon.color=0xffa6da95 \
    icon.font="$FONT_FACE:Bold:20.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=0 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:12.0" \
    label.drawing=yes

sketchybar --add item weather.moon q \
    --set weather.moon \
    background.color=0xAA7dc4e4 \
    background.padding_right=-1 \
    icon.color=0xff181926 \
    icon.font="$FONT_FACE:Bold:22.0" \
    icon.padding_left=4 \
    icon.padding_right=3 \
    label.drawing=off \
    --subscribe weather.moon mouse.clicked2

sketchybar --add item weather q \
    --set weather \
    icon= \
    icon.color=0xfff5bde6 \
    icon.font="$FONT_FACE:Bold:15.0" \
    update_freq=1800 \
    script="$PLUGIN_SHARED_DIR/weather.sh" \
    --subscribe weather system_woke

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add bracket current_space_bracket \
    current_space \
    current_space.separator \
    current_space.name \
     --subscribe current_space front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item wifi right \
    --set wifi \
    icon.color=0xff91D7E3 \
    label.drawing=true \
    update_freq=20 \
    script="$PLUGIN_DIR/wifi.sh"

sketchybar --add item volume right \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change


# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
