#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-desktop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

# Add custom event for aerospace workspace changes
sketchybar --add event aerospace_workspace_change

sketchybar --bar \
    height=25 \
    color=0x66494d64 \
    margin=0 \
    sticky=on \
    padding_left=0 \
    padding_right=0 \
    notch_width=188 \
    display=main

sketchybar --default \
    background.height=28 \
    icon.color=0xff24273a \
    icon.font="$FONT_FACE:Medium:20.0" \
    icon.padding_left=5 \
    icon.padding_right=2 \
    label.color=0xff24273a \
    label.font="$FONT_FACE:Bold:14.0" \
    label.y_offset=1 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5a97f \
    icon.font="$FONT_FACE:Medium:20.0" \
    icon.color=0xff24273a \
    icon.padding_left=5 \
    icon.padding_right=2 \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --add item current_space.separator left \
    --set current_space.separator \
    background.color=0x00000000 \
    background.padding_left=-3 \
    icon= \
    icon.color=0xfff5a97f \
    icon.font="$FONT_FACE:Bold:23.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item current_space.name left \
    --set current_space.name \
    background.color=0x00000000 \
    background.padding_right=5 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:14.0" \
    label.color=0xffcad3f5 \
    label.padding_left=2 \
    label.drawing=yes

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    icon= \
    icon.color=0xffa6da95 \
    icon.font="$FONT_FACE:Bold:23.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:14.0" \
    label.color=0xffcad3f5 \
    label.padding_left=5

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

# Add bracket for current_space items
sketchybar --add bracket current_space_bracket \
    current_space \
    current_space.separator \
    current_space.name \
    --subscribe current_space front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    background.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify right \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
