-- =============================================================================
-- KEYMAP DOCS GENERATOR
-- =============================================================================
-- Regenerates KEYMAPS.md from live mappings. Run with :GenKeymaps.
-- Also picks up lazy.nvim `keys = {}` triggers (they register real mappings
-- with descriptions before the plugin loads).

local M = {}

-- Must stay in sync with which-key spec in plugins/ui.lua
local LEADER_GROUPS = {
  f = '[F]ind',
  c = '[C]ode',
  g = '[G]it',
  j = '[J]ujutsu',
  r = '[R]un',
  h = '[H]arpoon',
  x = 'Toggle [X]',
  u = '[U]tils',
  a = '[A]I',
  b = '[B]uffer',
}

local MODES = { 'n', 'v', 'x', 'i', 't', 'o', 's' }

-- Skip user-invisible mappings: plugin internals and nvim built-in defaults.
local function is_noise(map)
  if map.lhs:match('^<Plug>') then return true end
  local d = map.desc or ''
  if d:match('^:help ') then return true end
  if d:match('^:help%-') then return true end
  if d:match('%-default$') then return true end
  -- Bare :command descriptions (e.g. ":previous", ":bnext") are nvim defaults
  if d:match('^:[%w_]+$') then return true end
  return false
end

local function display_lhs(lhs, leader)
  if #leader == 0 then return lhs end
  if lhs:sub(1, #leader) ~= leader then return lhs end
  local rest = lhs:sub(#leader + 1)
  -- Double-leader: show as <leader><leader>
  if rest:sub(1, #leader) == leader then
    return '<leader><leader>' .. rest:sub(#leader + 1)
  end
  return '<leader>' .. rest
end

local function collect()
  local leader = vim.g.mapleader or '\\'
  local seen, entries = {}, {}
  for _, mode in ipairs(MODES) do
    for _, map in ipairs(vim.api.nvim_get_keymap(mode)) do
      if map.desc and map.desc ~= '' and not is_noise(map) then
        local key = mode .. ':' .. map.lhs
        if not seen[key] then
          seen[key] = true
          table.insert(entries, {
            mode = mode,
            lhs = map.lhs,
            desc = map.desc,
            is_leader = #leader > 0 and map.lhs:sub(1, #leader) == leader,
          })
        end
      end
    end
  end
  return entries, leader
end

local function escape_md(s)
  return (s:gsub('|', '\\|'))
end

function M.generate()
  local entries, leader = collect()

  local groups, leader_misc, misc = {}, {}, {}
  for _, e in ipairs(entries) do
    if e.is_leader and #e.lhs > #leader then
      local prefix = e.lhs:sub(#leader + 1, #leader + 1)
      local name = LEADER_GROUPS[prefix]
      if name then
        groups[name] = groups[name] or {}
        table.insert(groups[name], e)
      else
        table.insert(leader_misc, e)
      end
    else
      table.insert(misc, e)
    end
  end

  local function sort_entries(list)
    table.sort(list, function(a, b)
      if a.lhs ~= b.lhs then return a.lhs < b.lhs end
      return a.mode < b.mode
    end)
  end
  for _, list in pairs(groups) do sort_entries(list) end
  sort_entries(leader_misc)
  sort_entries(misc)

  local ordered = vim.tbl_keys(groups)
  table.sort(ordered)

  local lines = {
    '# Keymaps',
    '',
    '_Generated by `:GenKeymaps` — do not edit manually._',
    '',
    string.format('_%d mappings collected at %s._', #entries, os.date('%Y-%m-%d %H:%M')),
    '',
  }

  local function render(list)
    table.insert(lines, '| Mode | Key | Description |')
    table.insert(lines, '| --- | --- | --- |')
    for _, e in ipairs(list) do
      table.insert(lines, string.format(
        '| `%s` | `%s` | %s |',
        e.mode,
        escape_md(display_lhs(e.lhs, leader)),
        escape_md(e.desc)
      ))
    end
    table.insert(lines, '')
  end

  for _, name in ipairs(ordered) do
    table.insert(lines, '## ' .. name)
    table.insert(lines, '')
    render(groups[name])
  end

  if #leader_misc > 0 then
    table.insert(lines, '## Quick Access (ungrouped <leader>)')
    table.insert(lines, '')
    render(leader_misc)
  end

  if #misc > 0 then
    table.insert(lines, '## Global (non-leader)')
    table.insert(lines, '')
    render(misc)
  end

  local path = vim.fn.stdpath('config') .. '/KEYMAPS.md'
  local f, err = io.open(path, 'w')
  if not f then
    vim.notify('GenKeymaps: ' .. tostring(err), vim.log.levels.ERROR)
    return
  end
  f:write(table.concat(lines, '\n'))
  f:close()
  vim.notify(string.format('Wrote %s (%d keymaps)', path, #entries), vim.log.levels.INFO)
end

vim.api.nvim_create_user_command(
  'GenKeymaps',
  M.generate,
  { desc = 'Regenerate KEYMAPS.md from current mappings' }
)

return M
