-- =============================================================================
-- UNIFIED THEME SYSTEM — palette-driven
-- =============================================================================
-- Palettes are defined below. current-theme.lua (auto-generated by
-- scripts/switch-theme.sh) records which palette is active. Cycle palettes
-- from inside nvim with <leader>xt; that shells out to switch-theme so all
-- tools (tmux, ghostty, starship, fish) stay in sync.

local M = {}

-- =============================================================================
-- PALETTE DEFINITIONS
-- =============================================================================
-- Each palette holds the full set of tones the highlight function needs.
-- To add a palette:
--   1. Drop a shell file in shared/palettes/<name>.sh (for shell tools)
--   2. Add a Lua entry here with the same colors + derived tones
--   3. Run `switch-theme <name>` — no code changes needed elsewhere.

local palettes = {
  ['intellij-dark'] = {
    -- JetBrains New UI Dark (IntelliJ/RustRover 2025+)
    -- Source: platform-resources/src/themes/expUI/expUI_darkScheme.xml
    variant = 'dark',
    colorscheme = 'minimal',
    bg = '#1e1f22',
    fg = '#bcbec4',
    surface = '#2b2d30',
    highlight = '#214283',       -- selection/visual (matches new UI player blue at ~45% on bg)
    cursor_line = '#26282e',
    gray = '#6f737a',
    comment = '#7a7e85',
    border = '#393b40',
    line_nr = '#4b5059',
    cursor_line_nr = '#a1a3ab',
    muted = '#6f737a',
    blue = '#56a8f5',
    blue_bright = '#57aaf7',     -- method declaration / static method
    green = '#6aab73',
    doc = '#5f826b',
    purple = '#c77dbb',          -- constants, fields (instance + static)
    type_color = '#6fafbd',      -- new UI: types are cyan-teal, split from purple
    teal = '#16baac',            -- type parameter
    pink = '#c77dbb',
    red = '#f75464',
    yellow = '#f2c55c',
    orange = '#cf8e6d',
    cyan = '#2aacb8',
    attribute = '#d5b778',       -- new UI: golden tan (was olive #b3ae60)
    attribute_muted = '#bababa',
    tool_select = '#424449',     -- tool-window selection (element.selected ≈ 60% α on bg)
    folder_icon = '#d5b778',     -- warm tan, matches JetBrains folder glyphs
    diff_add = '#2a3b2d',
    diff_change = '#2a3045',
    diff_delete = '#3b2a2d',
    diff_text = '#3a4560',
    dap_stopped = '#3a3529',
  },

  ['intellij-light'] = {
    variant = 'light',
    colorscheme = 'oxocarbon',
    bg = '#f7f8fa',
    fg = '#080808',
    surface = '#eef0f3',
    highlight = '#d4e2ff',
    cursor_line = '#eef0f3',
    gray = '#8c8c8c',
    comment = '#8c8c8c',
    border = '#d1d1d1',
    line_nr = '#8c8c8c',
    cursor_line_nr = '#0065cf',
    muted = '#8c8c8c',
    blue = '#0065cf',
    blue_bright = '#0065cf',
    green = '#067d17',
    doc = '#067d17',
    purple = '#871094',
    teal = '#9f0071',
    pink = '#871094',
    red = '#cf3737',
    yellow = '#9e880d',
    orange = '#cf6a21',
    cyan = '#2aacb8',
    attribute = '#9e880d',
    attribute_muted = '#4a4a4a',
    diff_add = '#dcf5de',
    diff_change = '#dce8f5',
    diff_delete = '#f5dcdc',
    diff_text = '#c4d8f0',
    dap_stopped = '#f5e8c0',
  },

  ['onyx'] = {
    variant = 'dark',
    colorscheme = 'minimal',
    -- Pillars (exact): Onyx bg, Desert Sand fg, Mauve Shadow highlight.
    bg = '#151311',
    fg = '#eed3ba',
    surface = '#251e1b',
    highlight = '#4b262f',
    cursor_line = '#1e1816',
    gray = '#a08d7d',
    comment = '#9a8472',
    border = '#3a2e2a',
    line_nr = '#6b5d52',
    cursor_line_nr = '#eed3ba',
    muted = '#a08d7d',
    blue = '#9fbde0',
    blue_bright = '#b0cbe8',
    green = '#b8c47c',
    doc = '#9ab070',
    purple = '#c28a9a',
    teal = '#c28a9a',
    pink = '#d48a9c',
    red = '#e87462',
    yellow = '#f0c97d',
    orange = '#eda078',
    cyan = '#a8c8c2',
    attribute = '#d4bc70',
    attribute_muted = '#c4b5a0',
    tool_select = '#352a26',       -- warm dark taupe — subtle tree selection
    folder_icon = '#d4bc70',       -- warm amber folder glyphs
    diff_add = '#2d3220',
    diff_change = '#2b2536',
    diff_delete = '#4a2826',
    diff_text = '#5b384a',
    dap_stopped = '#4d3228',
  },

  ['catppuccin-mocha'] = {
    variant = 'dark',
    colorscheme = 'minimal',
    bg = '#1e1e2e',
    fg = '#cdd6f4',
    surface = '#181825',
    highlight = '#313244',
    cursor_line = '#181825',
    gray = '#6c7086',
    comment = '#9399b2',          -- overlay2 — readable comments
    border = '#45475a',
    line_nr = '#585b70',           -- surface2
    cursor_line_nr = '#cdd6f4',
    muted = '#6c7086',
    blue = '#89b4fa',
    blue_bright = '#74c7ec',       -- sapphire
    green = '#a6e3a1',
    doc = '#a6e3a1',
    purple = '#cba6f7',            -- mauve
    teal = '#94e2d5',
    pink = '#f5c2e7',
    red = '#f38ba8',
    yellow = '#f9e2af',
    orange = '#fab387',            -- peach
    cyan = '#89dceb',              -- sky
    attribute = '#f9e2af',
    attribute_muted = '#bac2de',   -- subtext1
    diff_add = '#1e2d27',
    diff_change = '#1e2330',
    diff_delete = '#2d1e23',
    diff_text = '#2a3a5a',
    dap_stopped = '#3a3422',
  },

  ['tokyonight'] = {
    variant = 'dark',
    colorscheme = 'minimal',
    bg = '#1a1b26',
    fg = '#c0caf5',
    surface = '#16161e',
    highlight = '#283457',
    cursor_line = '#1f2335',
    gray = '#565f89',
    comment = '#565f89',
    border = '#292e42',
    line_nr = '#3b4261',
    cursor_line_nr = '#c0caf5',
    muted = '#565f89',
    blue = '#7aa2f7',
    blue_bright = '#2ac3de',
    green = '#9ece6a',
    doc = '#73daca',
    purple = '#bb9af7',
    teal = '#73daca',
    pink = '#ff007c',
    red = '#f7768e',
    yellow = '#e0af68',
    orange = '#ff9e64',
    cyan = '#7dcfff',
    attribute = '#e0af68',
    attribute_muted = '#a9b1d6',
    diff_add = '#1b2b28',
    diff_change = '#1b2538',
    diff_delete = '#2b1f27',
    diff_text = '#3b4261',
    dap_stopped = '#3d3014',
  },

  ['gruvbox-dark'] = {
    variant = 'dark',
    colorscheme = 'minimal',
    bg = '#282828',
    fg = '#ebdbb2',
    surface = '#3c3836',
    highlight = '#504945',
    cursor_line = '#32302f',
    gray = '#a89984',              -- fg4, lighter than default for readability
    comment = '#928374',
    border = '#665c54',
    line_nr = '#7c6f64',
    cursor_line_nr = '#fabd2f',
    muted = '#928374',
    blue = '#83a598',
    blue_bright = '#458588',
    green = '#b8bb26',
    doc = '#8ec07c',
    purple = '#d3869b',
    teal = '#8ec07c',
    pink = '#d3869b',
    red = '#fb4934',
    yellow = '#fabd2f',
    orange = '#fe8019',
    cyan = '#8ec07c',
    attribute = '#fabd2f',
    attribute_muted = '#bdae93',
    diff_add = '#34381b',
    diff_change = '#0e3b43',
    diff_delete = '#402120',
    diff_text = '#1d4a3a',
    dap_stopped = '#4a3a1c',
  },

  ['rose-pine'] = {
    variant = 'dark',
    colorscheme = 'minimal',
    bg = '#191724',
    fg = '#e0def4',
    surface = '#1f1d2e',
    highlight = '#403d52',
    cursor_line = '#21202e',       -- highlight_low
    gray = '#908caa',              -- subtle
    comment = '#6e6a86',           -- muted
    border = '#26233a',
    line_nr = '#6e6a86',
    cursor_line_nr = '#e0def4',
    muted = '#6e6a86',
    blue = '#31748f',              -- pine
    blue_bright = '#9ccfd8',
    green = '#9ccfd8',             -- foam doubles as green for readability
    doc = '#9ccfd8',
    purple = '#c4a7e7',            -- iris
    teal = '#9ccfd8',              -- foam
    pink = '#ebbcba',              -- rose
    red = '#eb6f92',               -- love
    yellow = '#f6c177',            -- gold
    orange = '#ebbcba',            -- rose as orange
    cyan = '#9ccfd8',
    attribute = '#f6c177',
    attribute_muted = '#908caa',
    diff_add = '#1e2d2a',
    diff_change = '#2a1f33',
    diff_delete = '#3d1f2e',
    diff_text = '#524f67',
    dap_stopped = '#3d3022',
  },

  ['nord'] = {
    variant = 'dark',
    colorscheme = 'minimal',
    bg = '#2e3440',
    fg = '#d8dee9',
    surface = '#3b4252',
    highlight = '#434c5e',
    cursor_line = '#353b49',
    gray = '#616e88',              -- lifted from nord3 for comment visibility
    comment = '#616e88',
    border = '#434c5e',
    line_nr = '#4c566a',
    cursor_line_nr = '#eceff4',
    muted = '#4c566a',
    blue = '#81a1c1',              -- nord9
    blue_bright = '#5e81ac',       -- nord10
    green = '#a3be8c',
    doc = '#8fbcbb',
    purple = '#b48ead',
    teal = '#8fbcbb',              -- nord7
    pink = '#b48ead',
    red = '#bf616a',
    yellow = '#ebcb8b',
    orange = '#d08770',
    cyan = '#88c0d0',              -- nord8
    attribute = '#ebcb8b',
    attribute_muted = '#d8dee9',
    diff_add = '#2d3a36',
    diff_change = '#2a3347',
    diff_delete = '#3f2d37',
    diff_text = '#4c566a',
    dap_stopped = '#3a3a28',
  },

  ['kanagawa'] = {
    variant = 'dark',
    colorscheme = 'minimal',
    bg = '#1f1f28',
    fg = '#dcd7ba',
    surface = '#2a2a37',
    highlight = '#363646',
    cursor_line = '#252535',
    gray = '#727169',
    comment = '#727169',
    border = '#54546d',
    line_nr = '#54546d',
    cursor_line_nr = '#c8c093',
    muted = '#727169',
    blue = '#7e9cd8',              -- crystalBlue
    blue_bright = '#7fb4ca',       -- springBlue
    green = '#98bb6c',             -- springGreen
    doc = '#8a9a7b',
    purple = '#957fb8',            -- oniViolet
    teal = '#7aa89f',              -- waveAqua2
    pink = '#d27e99',              -- sakuraPink
    red = '#e46876',               -- waveRed
    yellow = '#e6c384',            -- carpYellow
    orange = '#ffa066',            -- surimiOrange
    cyan = '#7fb4ca',              -- springBlue
    attribute = '#e6c384',
    attribute_muted = '#a6a69c',
    diff_add = '#2b3328',
    diff_change = '#252535',
    diff_delete = '#43242b',
    diff_text = '#49443c',
    dap_stopped = '#43412b',
  },
}

-- =============================================================================
-- HIGHLIGHTS
-- =============================================================================

local function apply_highlights(p)
  local hl = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end

  -- Palettes that predate the type/constant split fall back to purple.
  local type_color = p.type_color or p.purple

  -- Core UI
  hl('Normal', { bg = p.bg, fg = p.fg })
  hl('NormalNC', { bg = p.bg, fg = p.fg })   -- non-current window: stay on palette bg
  hl('NormalFloat', { bg = p.surface, fg = p.fg })
  hl('Pmenu', { bg = p.surface, fg = p.fg })
  hl('PmenuSel', { bg = p.highlight, fg = p.fg, bold = true })
  hl('Visual', { bg = p.highlight })
  hl('CursorLine', { bg = p.cursor_line })
  hl('CursorLineNr', { fg = p.cursor_line_nr, bg = p.cursor_line, bold = true })
  hl('ColorColumn', { bg = p.surface })
  hl('SignColumn', { bg = p.bg })
  hl('LineNr', { fg = p.line_nr, bg = p.bg })
  hl('VertSplit', { fg = p.border, bg = 'NONE' })
  hl('WinSeparator', { fg = p.border, bg = 'NONE' })
  hl('StatusLine', { fg = p.fg, bg = p.surface })
  hl('StatusLineNC', { fg = p.muted, bg = p.bg })
  hl('TabLine', { fg = p.muted, bg = p.surface })
  hl('TabLineFill', { bg = p.bg })
  hl('TabLineSel', { fg = p.fg, bg = p.bg, bold = true })

  -- NeoTree — tool window matches editor bg. Selection uses a neutral "tool
  -- window" gray (like JetBrains element.selected), not the blue editor visual.
  local tool_select = p.tool_select or p.highlight
  local folder_icon = p.folder_icon or p.attribute or p.yellow
  hl('NeoTreeNormal',        { bg = p.bg, fg = p.fg })
  hl('NeoTreeNormalNC',      { bg = p.bg, fg = p.fg })
  hl('NeoTreeEndOfBuffer',   { bg = p.bg, fg = p.bg })
  hl('NeoTreeWinSeparator',  { bg = p.bg, fg = p.border })
  hl('NeoTreeCursorLine',    { bg = tool_select })
  hl('NeoTreeDirectoryName', { fg = p.fg })
  hl('NeoTreeDirectoryIcon', { fg = folder_icon })
  hl('NeoTreeFileName',      { fg = p.fg })
  hl('NeoTreeFileIcon',      { fg = p.muted })
  hl('NeoTreeRootName',      { fg = p.fg, bold = true })
  hl('NeoTreeExpander',      { fg = p.muted })
  hl('NeoTreeIndentMarker',  { fg = p.border })
  hl('NeoTreeFloatBorder',   { bg = p.surface, fg = p.border })
  hl('NeoTreeFloatTitle',    { bg = p.surface, fg = p.fg, bold = true })
  hl('NeoTreeTitleBar',      { bg = p.surface, fg = p.fg, bold = true })
  hl('NeoTreeModified',      { fg = p.orange })
  hl('NeoTreeGitAdded',      { fg = p.green })
  hl('NeoTreeGitModified',   { fg = p.blue })
  hl('NeoTreeGitDeleted',    { fg = p.red })
  hl('NeoTreeGitRenamed',    { fg = p.blue })
  hl('NeoTreeGitUntracked',  { fg = p.orange })
  hl('NeoTreeGitStaged',     { fg = p.green })
  hl('NeoTreeGitUnstaged',   { fg = p.yellow })
  hl('NeoTreeGitConflict',   { fg = p.red, bold = true })
  hl('NeoTreeGitIgnored',    { fg = p.muted })
  hl('NeoTreeDotfile',       { fg = p.muted })
  hl('NeoTreeHiddenByName',  { fg = p.muted })

  -- Syntax
  hl('Comment', { fg = p.comment, italic = true })
  hl('Keyword', { fg = p.orange, bold = true })
  hl('Conditional', { fg = p.orange, bold = true })
  hl('Repeat', { fg = p.orange, bold = true })
  hl('Statement', { fg = p.orange, bold = true })
  hl('StorageClass', { fg = p.orange, bold = true })
  hl('String', { fg = p.green })
  hl('Character', { fg = p.green })
  hl('Number', { fg = p.cyan })
  hl('Boolean', { fg = p.orange, bold = true })
  hl('Float', { fg = p.cyan })
  hl('Function', { fg = p.blue })
  hl('Identifier', { fg = p.fg })
  hl('Type', { fg = type_color })
  hl('Constant', { fg = p.purple, italic = true })
  hl('Macro', { fg = p.purple, italic = true })
  hl('PreProc', { fg = p.orange, bold = true })
  hl('Include', { fg = p.orange, bold = true })
  hl('Define', { fg = p.orange, bold = true })
  hl('Operator', { fg = p.fg })
  hl('Delimiter', { fg = p.fg })
  hl('Special', { fg = p.orange })
  hl('Tag', { fg = p.fg })
  hl('Title', { fg = p.blue, bold = true })
  hl('Todo', { fg = p.attribute, bold = true })
  hl('Error', { fg = p.red })
  hl('WarningMsg', { fg = p.yellow })

  -- LSP
  hl('LspInlayHint', { fg = p.muted, bg = p.cursor_line, italic = true })
  hl('LspReferenceText', { underline = true })
  hl('LspReferenceRead', { underline = true })
  hl('LspReferenceWrite', { underline = true, bold = true })

  -- Treesitter
  hl('@keyword', { fg = p.orange, bold = true })
  hl('@keyword.function', { fg = p.orange, bold = true })
  hl('@keyword.return', { fg = p.orange, bold = true })
  hl('@keyword.operator', { fg = p.orange, bold = true })
  hl('@keyword.import', { fg = p.orange, bold = true })
  hl('@keyword.modifier', { fg = p.orange, bold = true })
  hl('@conditional', { fg = p.orange, bold = true })
  hl('@repeat', { fg = p.orange, bold = true })
  hl('@exception', { fg = p.orange, bold = true })
  hl('@string', { fg = p.green })
  hl('@string.escape', { fg = p.orange, bold = true })
  hl('@string.regex', { fg = p.orange })
  hl('@string.special', { fg = p.orange })
  hl('@number', { fg = p.cyan })
  hl('@boolean', { fg = p.orange, bold = true })
  hl('@float', { fg = p.cyan })
  hl('@function', { fg = p.blue })
  hl('@function.call', { fg = p.fg })
  hl('@function.builtin', { fg = p.blue })
  hl('@function.macro', { fg = p.purple, italic = true })
  hl('@method', { fg = p.blue_bright })
  hl('@method.call', { fg = p.blue_bright })
  hl('@constructor', { fg = type_color })
  hl('@type', { fg = type_color })
  hl('@type.builtin', { fg = type_color, bold = true })
  hl('@type.qualifier', { fg = p.orange, bold = true })
  hl('@variable', { fg = p.fg })
  hl('@variable.builtin', { fg = p.orange, bold = true })
  hl('@variable.parameter', { fg = p.fg })
  hl('@variable.member', { fg = p.purple })
  hl('@property', { fg = p.purple })
  hl('@field', { fg = p.purple })
  hl('@parameter', { fg = p.fg })
  hl('@constant', { fg = p.purple, italic = true })
  hl('@constant.builtin', { fg = p.orange, bold = true })
  hl('@constant.macro', { fg = p.purple, italic = true })
  hl('@comment', { fg = p.comment, italic = true })
  hl('@operator', { fg = p.fg })
  hl('@punctuation', { fg = p.fg })
  hl('@punctuation.bracket', { fg = p.fg })
  hl('@punctuation.delimiter', { fg = p.fg })
  hl('@punctuation.special', { fg = p.orange })
  hl('@tag', { fg = p.fg })
  hl('@tag.attribute', { fg = p.attribute_muted })
  hl('@tag.delimiter', { fg = p.fg })
  hl('@attribute', { fg = p.attribute })
  hl('@annotation', { fg = p.attribute })
  hl('@namespace', { fg = p.fg })
  hl('@module', { fg = p.fg })
  hl('@label', { fg = p.purple })
  hl('@comment.documentation', { fg = p.doc, italic = true })
  hl('@type.parameter', { fg = p.teal })
  hl('@markup.heading', { fg = p.blue, bold = true })
  hl('@markup.link', { fg = p.blue, underline = true })
  hl('@markup.strong', { bold = true })
  hl('@markup.italic', { italic = true })
  hl('@markup.raw', { fg = p.green })

  -- Diagnostics
  hl('DiagnosticError', { fg = p.red })
  hl('DiagnosticWarn', { fg = p.yellow })
  hl('DiagnosticInfo', { fg = p.blue })
  hl('DiagnosticHint', { fg = p.green })

  -- DAP
  hl('DapStoppedLine', { bg = p.dap_stopped })
  hl('DapStopped', { fg = p.yellow, bg = p.dap_stopped })
  hl('DapBreakpoint', { fg = p.red })
  hl('DapBreakpointCondition', { fg = p.yellow })
  hl('DapLogPoint', { fg = p.blue })

  -- Flash
  hl('FlashLabel', { fg = p.bg, bg = p.yellow, bold = true })
  hl('FlashMatch', { fg = p.bg, bg = p.green })
  hl('FlashCurrent', { fg = p.bg, bg = p.blue, bold = true })
  hl('FlashBackdrop', { fg = p.muted })

  -- GitSigns
  hl('GitSignsAdd', { fg = p.green, bg = p.bg })
  hl('GitSignsChange', { fg = p.blue, bg = p.bg })
  hl('GitSignsDelete', { fg = p.red, bg = p.bg })

  -- Which-key
  hl('WhichKey', { fg = p.blue, bold = true })
  hl('WhichKeyGroup', { fg = p.purple })
  hl('WhichKeyDesc', { fg = p.fg })
  hl('WhichKeyFloat', { bg = p.surface })

  -- Telescope
  hl('TelescopeNormal', { bg = p.surface, fg = p.fg })
  hl('TelescopeBorder', { bg = p.surface, fg = p.border })
  hl('TelescopeSelection', { bg = p.highlight, fg = p.fg, bold = true })
  hl('TelescopeMatching', { fg = p.blue, bold = true })
  hl('TelescopePromptNormal', { bg = p.surface, fg = p.fg })
  hl('TelescopePromptBorder', { bg = p.surface, fg = p.border })
  hl('TelescopeResultsNormal', { bg = p.bg, fg = p.fg })
  hl('TelescopeResultsBorder', { bg = p.bg, fg = p.border })
  hl('TelescopePreviewNormal', { bg = p.bg, fg = p.fg })
  hl('TelescopePreviewBorder', { bg = p.bg, fg = p.border })

  -- Treesitter context
  hl('TreesitterContext', { bg = p.surface })
  hl('TreesitterContextLineNumber', { fg = p.line_nr, bg = p.surface })

  -- Search
  hl('Search', { bg = p.highlight, fg = p.fg })
  hl('IncSearch', { bg = p.yellow, fg = p.bg })
  hl('CurSearch', { bg = p.yellow, fg = p.bg })

  -- Diff
  hl('DiffAdd', { bg = p.diff_add })
  hl('DiffChange', { bg = p.diff_change })
  hl('DiffDelete', { bg = p.diff_delete })
  hl('DiffText', { bg = p.diff_text })

  -- Folds
  hl('Folded', { fg = p.muted, bg = p.surface })
  hl('FoldColumn', { fg = p.muted, bg = p.bg })

  -- Misc
  hl('NonText', { fg = p.border })
  hl('SpecialKey', { fg = p.border })
  hl('MatchParen', { bg = p.border, bold = true })
  hl('FloatBorder', { fg = p.border, bg = p.surface })
end

-- =============================================================================
-- PUBLIC API
-- =============================================================================

-- Read the active palette name from the generated current-theme.lua.
-- Returns "intellij-dark" on first run / missing file.
local function read_current()
  local ok, mod = pcall(require, 'custom.current-theme')
  if ok and type(mod) == 'table' and mod.name then
    return mod.name
  end
  return 'intellij-dark'
end

-- Apply the palette with the given name (or the currently-recorded one).
M.apply = function(name)
  name = name or read_current()
  local palette = palettes[name] or palettes['intellij-dark']

  vim.o.background = palette.variant
  -- Pcall so we don't crash on first load before the colorscheme plugin exists.
  pcall(vim.cmd, 'colorscheme ' .. palette.colorscheme)
  apply_highlights(palette)

  -- Tell lualine (and anyone else listening) to refresh with new colors.
  pcall(function()
    require('lualine').setup { options = { theme = M.lualine_theme() } }
  end)
end

-- Return the active palette table (loads the current one if nothing specified).
M.palette = function(name)
  return palettes[name or read_current()] or palettes['intellij-dark']
end

-- Build a lualine theme from the active palette. Flat, IntelliJ-style:
-- bar bg = surface, mode letter colored by mode.
M.lualine_theme = function()
  local p = M.palette()
  local mode = function(accent)
    return {
      a = { bg = p.surface, fg = accent, gui = 'bold' },
      b = { bg = p.surface, fg = p.fg },
      c = { bg = p.surface, fg = p.muted },
    }
  end
  return {
    normal = mode(p.blue),
    insert = mode(p.green),
    visual = mode(p.purple),
    replace = mode(p.red),
    command = mode(p.orange),
    inactive = {
      a = { bg = p.surface, fg = p.muted },
      b = { bg = p.surface, fg = p.muted },
      c = { bg = p.surface, fg = p.muted },
    },
  }
end

-- Reload current palette after switch-theme rewrote current-theme.lua.
M.reload = function()
  package.loaded['custom.current-theme'] = nil
  M.apply()
end

-- Cycle to the next palette by shelling out to switch-theme, which updates
-- every tool — then reload inside this nvim instance.
M.toggle_theme = function()
  vim.fn.system { vim.fn.expand('~/Projects/Sandbox/dotfiles/scripts/switch-theme.sh'), 'next' }
  M.reload()
end

M.setup = function()
  M.apply()
  vim.keymap.set('n', '<leader>xt', M.toggle_theme, { desc = 'Cycle [T]heme palette' })
end

return M
