# Auto-generated by scripts/switch-theme.sh.
# Palette: Onyx
# Sourced by config.fish — do not edit by hand.

# Syntax highlighting
set -g fish_color_normal eed3ba
set -g fish_color_command 9fbde0
set -g fish_color_keyword eda078
set -g fish_color_quote b8c47c
set -g fish_color_redirection a8c8c2
set -g fish_color_end eda078
set -g fish_color_error e87462
set -g fish_color_param eed3ba
set -g fish_color_comment a08d7d
set -g fish_color_operator a8c8c2
set -g fish_color_escape c28a9a
set -g fish_color_autosuggestion a08d7d
set -g fish_color_valid_path --underline
set -g fish_color_selection --background=4b262f
set -g fish_color_search_match --background=4b262f
set -g fish_color_cancel e87462

# Pager (tab completion menu)
set -g fish_pager_color_progress a08d7d
set -g fish_pager_color_prefix 9fbde0 --bold
set -g fish_pager_color_completion eed3ba
set -g fish_pager_color_description a08d7d
set -g fish_pager_color_selected_background --background=4b262f
