# Fish Shell Configuration

# Suppress greeting
set -g fish_greeting

if status is-interactive
	# Homebrew
	eval (/opt/homebrew/bin/brew shellenv)

	# Initialize Starship prompt
	set -gx STARSHIP_CONFIG ~/.config/starship/starship.toml
	starship init fish | source

	# Zoxide
	zoxide init fish | source

	# Palette colors — regenerated by scripts/switch-theme.sh
	if test -f $__fish_config_dir/colors.fish
		source $__fish_config_dir/colors.fish
	end

	# Aliases
	alias ts='~/Projects/Sandbox/dotfiles/scripts/start_project.sh'

	function book
		cd ~/Projects/Work/Kognitos/books/book-"$argv[1]"
	end

	function v2
		cd ~/Projects/Work/Kognitos/voyager/"$argv[1]"
	end

	function bdk
		cd ~/Projects/Work/Kognitos/bdk/"$argv[1]"
	end

end

# Function: ks
function ks
    if type -q bass
        # Use bass to source the bash script and import env changes
        bass source /Users/tomiberretta/Projects/Work/Kognitos/bdk/bdk-toolbox/scripts/k8s-context-switch/switch.sh $argv
    else
        bash /Users/tomiberretta/Projects/Work/Kognitos/bdk/bdk-toolbox/scripts/k8s-context-switch/switch.sh $argv
    end
end

function bdk-runtime
    argparse 'mode=?' 'transport=?' 'ngrok=?' 'grpc=?' 'http=?' 'otel=?' -- $argv
    or return

    if test (count $argv) -eq 0
        echo "Usage: bdk-run <book_path> [--mode=book] [--transport=ngrok] [--ngrok=TOKEN] [--grpc=40404] [--http=40404] [--otel=true]"
        return 1
    end

    set -l book_path $argv[1]

    cargo build; and \
    BDK_SERVER_MODE=(set -q _flag_mode; and echo $_flag_mode; or echo "book") \
    BDK_TRANSPORT_MODE=(set -q _flag_transport; and echo $_flag_transport; or echo "ngrok") \
    NGROK_AUTHTOKEN=(set -q _flag_ngrok; and echo $_flag_ngrok; or echo $NGROK_AUTHTOKEN) \
    BDK_GRPC_PORT=(set -q _flag_grpc; and echo $_flag_grpc; or echo "40404") \
    BDK_HTTP_PORT=(set -q _flag_http; and echo $_flag_http; or echo "40404") \
    OTEL_SDK_DISABLED=(set -q _flag_otel; and echo $_flag_otel; or echo "true") \
    BDK_RUNTIME_PYTHON_BOOK_PATH="$book_path" \
    ./target/debug/bdk-runtime
end

function fish-reload-all
    set -l file (test (count $argv) -gt 0; and echo $argv[1]; or echo $__fish_config_dir/config.fish)
    set -l count 0
    for pane in (tmux list-panes -a -F '#{pane_id}:#{pane_current_command}')
        set -l id (string split ':' $pane)[1]
        set -l cmd (string split ':' $pane)[2]
        if test "$cmd" = "fish"
            tmux send-keys -t $id "source $file" Enter
            set count (math $count + 1)
        end
    end
    echo "Reloaded in $count pane(s)"
end
